// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TsdNetCoreLab_EF.Entities;

#nullable disable

namespace TsdNetCoreLab6_EF.Migrations
{
    [DbContext(typeof(TsdAppDbContext))]
    [Migration("20260930011822_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TsdNetCoreLab6_EF.Models.TsdCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("TsdCategory");
                });

            modelBuilder.Entity("TsdNetCoreLab6_EF.Models.TsdProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("SalePrice")
                        .HasColumnType("float");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TsdCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TsdCategoryId");

                    b.ToTable("TsdProduct");
                });

            modelBuilder.Entity("TsdNetCoreLab6_EF.Models.TsdProducts", b =>
                {
                    b.HasOne("TsdNetCoreLab6_EF.Models.TsdCategory", "TsdCategory")
                        .WithMany("TsdProducts")
                        .HasForeignKey("TsdCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TsdCategory");
                });

            modelBuilder.Entity("TsdNetCoreLab6_EF.Models.TsdCategory", b =>
                {
                    b.Navigation("TsdProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
